import { Inter } from "next/font/google";
import "./globals.css";
import '../../public/pages/sass/base/base.scss'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./component/header";
import '@sweetalert2/theme-bootstrap-4/bootstrap-4.scss';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <Header />

      
          {children}
        </body>
      </html>
  );
}
